name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  AZURE_CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
  AZURE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
  IMAGE_NAME: chat-app
  ENV: ${{ secrets.ENV }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Secret Load
        run: |
          if [ -z "${{ AZURE_CONTAINER_REGISTRY_USERNAME }}" ]; then
            echo "❌ SECRET IS MISSING: Check if you used Repository vs Environment secrets."
            exit 1
          else
            echo "✅ Secret is loaded (length: ${#USER})"
          fi
        env:
          USER: ${{ AZURE_CONTAINER_REGISTRY_USERNAME }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ ENV }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd src/
          docker build -t ${{ AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ IMAGE_NAME }}:latest .
          docker push ${{ AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ IMAGE_NAME }}:latest
        env:
          AZURE_CONTAINER_REGISTRY: ${{ AZURE_CONTAINER_REGISTRY }}
          IMAGE_NAME: ${{ IMAGE_NAME }}